[package]
name = "snes_compress"
version = "0.1.4"
edition = "2021"
repository = "https://github.com/smedit/snes_compress/"
description = "A library for decompressing and recompressing data in SNES games."
license = "MIT"

[dependencies]
thiserror = "1.*"
