[package]
name = "snes_compress"
version = "0.1.0"
edition = "2021"
description = "A library for decompressing and recompressing data in SNES games."
license = "MIT"

[dependencies]
thiserror = "1.*"
